### ISSUE TITLE
IDs on answer blocks in Check your Answers

### ISSUE THREAD

**Issue by paulgain** [hmcts/one-per-page#61]
Throughout a journey a user may answer "No" multiple times to various questions, for example:

- Are you an Appointee? No
- Do you want to receive text message reminders? No
- Do you have a representative? No

At present it's not possible to verify whether a piece of text such as "No" exists within a section whilst on the `Check your answers` (CYA) page whilst running our end-to-end tests. We cannot simply say `I.see('No')` because there are 3 instances on the page.

We can address this issue by adding a class name to each section, we can then pass the class name as context, for example, `I.see('No', '.section-class-name')`. There would also be a modest gain in performance as we are narrowing down the search to the section, not the page.

In addition, we need to think about how we deal with multiple identical answers to varying questions within the same section.

**Comment by paulgain** [comment]
<img width="536" alt="unable-to-verify-these-answers-when-testing-e2e" src="https://user-images.githubusercontent.com/964268/33317831-56aa7280-d430-11e7-8ed3-cdad2a346f1a.png">

**Comment by paulgain** [comment]
<img width="634" alt="unable-to-grab-this-from-codecept" src="https://user-images.githubusercontent.com/964268/33318058-2cdb449c-d431-11e7-8ab0-f40cb348db1c.png">

**Comment by michaeldfallen** [comment]
Each answer block (created using the [`answer` macro](https://github.com/hmcts/look-and-feel/blob/master/templates/look-and-feel/components/check-your-answers.njk#L1)) should have an id that can be used to directly target the parts of it, for example:
```
$('#appointee .cya-answer').text === 'No';
$('#have-a-representative .cya-answer').text === 'No';
```

These IDs can be generated from the question content provided in each step by lowercasing and concatentating each word with hypens (`-`). It should also be explicitly configurable as with all our settings for answers.

**Comment by michaeldfallen** [comment]
satisfied by #84 

The divs that wrap each question-answer-change list item now has an ID formed from the question:
![screenshot from 2018-01-12 11-11-17](https://user-images.githubusercontent.com/1446145/34872593-635a283c-f789-11e7-974e-9e50ea9f2475.png)
