### ISSUE TITLE
Add another functionality

### ISSUE THREAD

**Issue by michaeldfallen** [hmcts/one-per-page#71]
The add another functionality will be built as a mini transaction that allows for a step to list (similar to check your answers) the answers of a number of other steps. 

Those steps will be linked in a small journey that the user follows to add another item to the list.

![image](https://user-images.githubusercontent.com/1446145/33562765-044a0f36-d90e-11e7-9128-9c8dc072290e.png)

The CompoundStep will allow a user to declare a number of steps that should be used in the sub journey:

```
class DatesYouCantAttend extends CompoundStep {
  steps() [
    return [Date]
  }
  next() {
    return goTo(the next step in the main journey);
  }
}
```

The CompoundStep will act as a facade, wiring the sub steps to itself and handling requests for them, delegating only the parts that those steps need to handle, e.g. declaring the form, rendering the template, etc. Storing the values in the session will be handled by the compound step.

**Comment by paulgain** [comment]
Yes, this is a nice solution. It's worth pointing out to some that this is a non JavaScript implementation, a fallback to a date picker.

**Comment by bendiggle** [comment]
This looks very good! What would happen when the JS date picker is implemented? Would it still go to the add another step or bypass it?

**Comment by michaeldfallen** [comment]
The JS date picker could POST to the Date Step, which would handle the payload as if it was a nonJS payload.

**Comment by michaeldfallen** [comment]
Satisfied by #84
